/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        transparent: 'transparent',
        white: '#fff',
        'off-white': '#f7f8f8',
        'transparent-white': 'rgba(255, 255, 255, 0.08)',
        background: '#000212',
        grey: '#858699',
        'grey-dark': '#222326',
        'primary-text': '#b4bcd0',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'washed-blue-50': '#f0f3ff',
        'washed-blue-100': '#d0daff',
        'washed-blue-200': '#bac9ff',
        'washed-blue-300': '#9ab0ff',
        'washed-blue-400': '#86a1ff',
        'washed-blue-500': '#6889ff',
        'washed-blue-600': '#5f7de8',
        'washed-blue-700': '#4a61b5',
        'washed-blue-800': '#394b8c',
        'washed-blue-900': '#2c3a6b',
        'washed-purple-50': '#f8f7ff',
        'washed-purple-100': '#e8e7ff',
        'washed-purple-200': '#dddcff',
        'washed-purple-300': '#cecbff',
        'washed-purple-400': '#c5c1ff',
        'washed-purple-500': '#b6b2ff',
        'washed-purple-600': '#a6a2e8',
        'washed-purple-700': '#817eb5',
        'washed-purple-800': '#64628c',
        'washed-purple-900': '#4c4b6b',
        'primary-blue-50': '#e6f0ff',
        'primary-blue-100': '#b2d1ff',
        'primary-blue-200': '#8cbaff',
        'primary-blue-300': '#589bff',
        'primary-blue-400': '#3787ff',
        'primary-blue-500': '#0569ff',
        'primary-blue-600': '#0560e8',
        'primary-blue-700': '#044bb5',
        'primary-blue-800': '#033a8c',
        'primary-blue-900': '#022c6b',
        'primary-purple-50': '#f1e6ff',
        'primary-purple-100': '#d3b0ff',
        'primary-purple-200': '#bd8aff',
        'primary-purple-300': '#9f54ff',
        'primary-purple-400': '#8d33ff',
        'primary-purple-500': '#7000ff',
        'primary-purple-600': '#6600e8',
        'primary-purple-700': '#5000b5',
        'primary-purple-800': '#3e008c',
        'primary-purple-900': '#2f006b',
        'Neutrals/neutrals-1': '#ffffff',
        'Neutrals/neutrals-2': '#fcfcfd',
        'Neutrals/neutrals-3': '#f5f5f6',
        'Neutrals/neutrals-4': '#f0f0f1',
        'Neutrals/neutrals-5': '#d9d9dc',
        'Neutrals/neutrals-6': '#c0bfc4',
        'Neutrals/neutrals-7': '#8d8c95',
        'Neutrals/neutrals-8': '#5b5966',
        'Neutrals/neutrals-9': '#464553',
        'Neutrals/neutrals-10': '#282637',
        'Neutrals/neutrals-11': '#201f30',
        'Neutrals/neutrals-12': '#161427',
        'Neutrals/neutrals-13': '#020014',
        'brand-washedPurple': '#b5b2ff',
        'brand-washedBlue': '#6889ff',
        'brand-primaryBlue': '#0469ff',
        'brand-primaryPurple': '#7000ff',
        'brand-dark': '#030014',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      backgroundImage: {
        'primary-gradient':
          'linear-gradient(92.88deg, rgb(69, 94, 181) 9.16%, rgb(86, 67, 204) 43.89%, rgb(103, 63, 215) 64.72%)',
        'page-gradient':
          'radial-gradient(ellipse 80% 50% at 50% -20%,rgba(120,119,198,0.3), transparent)',
        'hero-gradient':
          'radial-gradient(ellipse 50% 80% at 20% 40%,rgba(93,52,221,0.1),transparent), radial-gradient(ellipse 50% 80% at 80% 50%,rgba(120,119,198,0.15),transparent)',
        'hero-glow':
          'conic-gradient(from 230.29deg at 51.63% 52.16%, rgb(36, 0, 255) 0deg, rgb(0, 135, 255) 67.5deg, rgb(108, 39, 157) 198.75deg, rgb(24, 38, 163) 251.25deg, rgb(54, 103, 196) 301.88deg, rgb(105, 30, 255) 360deg)',
        'glow-lines':
          'linear-gradient(var(--direction),#9d9bf2 0.43%,#7877c6 14.11%,rgba(120,119,198,0) 62.95%)',
        'radial-faded':
          'radial-gradient(circle at bottom center,var(--color),transparent 70%)',
        'glass-gradient':
          'linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.05) 100%)',
      },
      boxShadow: {
        primary: 'rgb(80 63 205 / 50%) 0px 1px 40px',
      },
      transitionDelay: {
        0: '0ms',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'fade-in': {
          from: { opacity: 0, transform: 'translateY(-10px)' },
          to: { opacity: 1, transform: 'none' },
        },
        'image-rotate': {
          '0%': { transform: 'rotateX(25deg)' },
          '25%': { transform: 'rotateX(25deg) scale(0.9)' },
          '60%': { transform: 'none' },
          '100%': { transform: 'none' },
        },
        'image-glow': {
          '0%': {
            opacity: 0,
            'animation-timing-function': 'cubic-bezier(0.74,0.25,0.76,1)',
          },
          '10%': {
            opacity: 1,
            'animation-timing-function': 'cubic-bezier(0.12,0.01,0.08,0.99)',
          },
          '100%': {
            opacity: 0.2,
          },
        },
      },
      'sketch-lines': {
        '0%': { 'stroke-dashoffset': 1 },
        '50%': { 'stroke-dashoffset': 0 },
        '99%': { 'stroke-dashoffset': 0 },
        '100%': { visiblity: 'hidden' },
      },
      'glow-line-horizontal': {
        '0%': { opacity: 0, transform: 'translateX(0)' },
        '5%': { opacity: 1, transform: 'translateX(0)' },
        '90%': { opacity: 1 },
        '100%': { opacity: 0, transform: 'translateX(min(60vw, 45rem))' },
      },
      'glow-line-vertical': {
        '0%': { opacity: 0, transform: 'translateY(0)' },
        '5%': { opacity: 1, transform: 'translateY(0)' },
        '90%': { opacity: 1 },
        '100%': { opacity: 0, transform: 'translateY(min(21vw, 45rem))' },
      },
      zap: {
        '0%, 9%, 11%, 100% ': {
          fill: 'transparent',
        },
        '10%': {
          fill: 'white',
        },
      },
      bounce: {
        '50%': {
          transform: 'scale(0.98)',
        },
      },
      // spacing: {
      //   0: '0',
      //   1: '0.4rem',
      //   2: '0.8rem',
      //   3: '1.2rem',
      //   4: '1.6rem',
      //   5: '2rem',
      //   6: '2.4rem',
      //   7: '2.8rem',
      //   8: '3.2rem',
      //   9: '3.6rem',
      //   10: '4rem',
      //   11: '4.4rem',
      //   12: '4.8rem',
      //   13: '5.2rem',
      //   14: '5.6rem',
      //   15: '6rem',
      //   16: '6.4rem',
      //   'navigation-height': 'var(--navigation-height)',
      // },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 1000ms var(--animation-delay, 0ms) ease forwards',
        'image-rotate': 'image-rotate 1400ms ease forwards',
        'image-glow': 'image-glow 4100ms 600ms ease-out forwards',
        'sketch-lines': 'sketch-lines 1200ms ease-out forwards',
        'glow-line-horizontal':
          'glow-line-horizontal var(--animation-duration) ease-in forwards',
        'glow-line-vertical':
          'glow-line-vertical var(--animation-duration) ease-in forwards',
        zap: 'zap 2250ms calc(var(--index) * 20ms) linear infinite',
        bounce: '240ms ease 0s 1 running bounce',
      },
    },
  },
  // plugins: [require('tailwindcss-animate')],
  plugins: [],
};
